site_name: Epsilon
nav:
  - Home: index.md
  - Getting Started: 'getting-started.md'
  - Playground : 'playground'
  - Download : 'download/index.md'
  - Documentation:
    - Overview: 'doc/index.md'
    - Model Connectivity: 'doc/emc.md'
    - Languages:
        - Object Language (EOL): 'doc/eol.md'
        - Code Generation (EGL): 'doc/egl.md'
        - Code Generation (EGX): 'doc/egx.md'
        - Model Validation (EVL): 'doc/evl.md'
        - Model Transformation (ETL): 'doc/etl.md'
        - Model Comparison (ECL): 'doc/ecl.md'
        - Model Merging (EML): 'doc/eml.md'
        - Pattern Matching (EPL): 'doc/epl.md'
        - Model Migration (Flock): 'doc/flock.md'
        - Model Generation (EMG): 'doc/emg.md'
        - Unit Testing (EUnit): 'doc/eunit.md'
        - Dataset Extraction (Pinset): 'doc/pinset/index.md'
        - Wizard Language (EWL): 'doc/ewl.md'
    - Tools:
        - Picto: 'doc/picto/index.md'
        - Flexmi: 'doc/flexmi/index.md'
        - Eugenia: 'doc/eugenia/index.md'
        - Exeed: 'doc/exeed/index.md'
        - Modelink: 'doc/modelink/index.md'
        - HUTN: 'doc/hutn.md'
        - Workflow (Ant tasks): 'doc/workflow.md'
    - Articles: 'doc/articles/index.md'
    - Examples: 'examples.md'
    - Screencasts: 'https://www.youtube.com/epsilondevs'
    - Lectures: 'https://www.youtube.com/playlist?list=PLRwHao6Ue0YUecg7vEUQTrtySIWwrd_mI'
    - Javadoc:
      - Stable: 'https://download.eclipse.org/epsilon/stable-javadoc/'
      - Interim: 'https://download.eclipse.org/epsilon/interim-javadoc/'
      - '2.4.0': 'https://download.eclipse.org/epsilon/2.4.0-javadoc/'
      - '2.3.0': 'https://download.eclipse.org/epsilon/2.3.0-javadoc/'
      - '2.2.0': 'https://download.eclipse.org/epsilon/2.2.0-javadoc/'
      - '2.1.0': 'https://download.eclipse.org/epsilon/2.1.0-javadoc/'
  - Issues:
      - Report a new issue: 'https://github.com/eclipse/epsilon/issues/new/choose'
      - View open issues: 'https://github.com/eclipse/epsilon/issues'
      - Bugzilla (legacy): 'https://bugs.eclipse.org/bugs/buglist.cgi?product=epsilon&cmdtype=doit&order=Reuse+same+sort+as+last+time'
  - Community:
      - Who is using Epsilon?:
        - Industry: 'users/index.md'
        - Education: 'users/education.md'
        - Open-source Projects: 'users/open-source.md'
      - Who is developing Epsilon?: 'https://projects.eclipse.org/projects/modeling.epsilon/who'
      - How can I support Epsilon?: 'https://ko-fi.com/eclipseepsilon'
      - Forum: 'https://www.eclipse.org/forums/index.php/f/22/'
      - Professional Services: professional-services
      - Social Media:
        - Twitter: 'https://twitter.com/eclipseepsilon'
        - YouTube: 'https://youtube.com/epsilondevs'
      - Epsilon Labs: 'labs.md'
      - Frequently Asked Questions: 'faq.md'
  - Branding: 'branding/index.md'
theme:
  name: material
  custom_dir: custom_theme
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.footer
  logo: 'assets/images/epsilon-white-background.png'
  favicon: 'assets/images/favicon.png'
  palette:
    primary: 'black'
    accent: 'orange'
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/eclipseepsilon
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/epsilondevs
repo_name: 'Epsilon @ GitHub'
repo_url: 'https://github.com/eclipse/epsilon'
edit_uri: ../epsilon-website/edit/master/mkdocs/docs/
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid mermaid-100
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: mermaid-90
          class: mermaid mermaid-90
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: mermaid-80
          class: mermaid mermaid-80
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: mermaid-70
          class: mermaid mermaid-70
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: mermaid-60
          class: mermaid mermaid-60
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: mermaid-50
          class: mermaid mermaid-50
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: mermaid-40
          class: mermaid mermaid-40
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: mermaid-30
          class: mermaid mermaid-30
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: eol
          class: prettyprint lang-eol
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: etl
          class: prettyprint lang-etl
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: ecl
          class: prettyprint lang-ecl
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: eml
          class: prettyprint lang-eml
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: epl
          class: prettyprint lang-epl
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: evl
          class: prettyprint lang-evl
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: mig
          class: prettyprint lang-mig
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: eunit
          class: prettyprint lang-eol
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: egx
          class: prettyprint lang-egx
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: egl
          class: prettyprint lang-egl
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: emf
          class: prettyprint lang-emf
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: pinset
          class: prettyprint lang-pinset
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.smartsymbols
  - meta
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
plugins:
    - exclude:
        glob:
          - playground/cypress/*
          - playground/node_modules/*
          - playground/package-lock.json
          - playground/cypress.config.js
          - playground/webpack.config.js
          - playground/package.json
    - search
    - macros:
        j2_block_start_string: '{{{%'
        j2_block_end_string: '%}}}'
        j2_variable_start_string: '{{{'
        j2_variable_end_string: '}}}'
    - redirects:
        redirect_maps:
            'forum.md': 'https://www.eclipse.org/forums/index.php/f/22/'
            'doc/screencasts.md' : 'https://www.youtube.com/epsilondevs'
            'doc/lectures.md' : 'https://www.youtube.com/playlist?list=PLRwHao6Ue0YUecg7vEUQTrtySIWwrd_mI'
            'doc/articles/emfatic.md': 'https://www.eclipse.org/emfatic'
            'doc/articles/eugenia-gmf-tutorial/index.md': 'https://www.eclipse.org/epsilon/doc/eugenia'
            'doc/articles/flexmi/index.md': 'https://www.eclipse.org/epsilon/doc/flexmi'
            'doc/articles/picto/index.md': 'https://www.eclipse.org/epsilon/doc/picto'
            'doc/articles/exeed-reference/index.md': 'https://www.eclipse.org/epsilon/doc/exeed'


copyright: 'Copyright Â© <a href="https://www.eclipse.org">Eclipse Foundation, Inc.</a> All Rights Reserved <br/> <a href="https://www.eclipse.org/legal/privacy.php">Privacy Policy</a> &centerdot; <a href="https://www.eclipse.org/legal/termsofuse.php">Terms of Use</a> &centerdot; <a href="https://www.eclipse.org/legal/copyright.php">Copyright Agent</a>  &centerdot; <a href="https://www.eclipse.org/legal/">Legal</a><p><img src="https://eclipse.dev/epsilon/assets/images/eclipse-foundation-logo.svg"/></p>'
extra_css:
  - 'assets/stylesheets/mermaid.css'
  - 'assets/javascript/google-code-prettify/prettify.css'
  #- 'assets/stylesheets/tabbed.css'
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.css
  - 'assets/stylesheets/slick.css'
  - 'assets/stylesheets/slick-theme.css'
  - 'assets/stylesheets/extra.css'

extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js
  - 'assets/javascript/mermaid.js'
  - 'assets/javascript/jquery.js'
  - 'assets/javascript/slick.min.js'
  - 'assets/javascript/google-code-prettify/prettify.js'
  - 'assets/javascript/google-code-prettify/lang-emfatic.js'
  - 'assets/javascript/google-code-prettify/lang-epsilon.js'
  - 'assets/javascript/google-code-prettify/prettyprint.js'
  - 'assets/javascript/extra.js'
  - https://w.appzi.io/w.js?token=jlv6W
google_analytics:
  - UA-184785655-1
  - auto
